# Generated by Django 4.0.2 on 2022-04-10 19:21

from django.db import migrations, models
import rss_scrapper.models.rss_source


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('last_updated_at', models.CharField(default=rss_scrapper.models.rss_source.now, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
