# Generated by Django 4.0.2 on 2022-04-03 10:13

from django.db import migrations, models
import rss_scrapper.models.rss_source


class Migration(migrations.Migration):

    dependencies = [
        ('rss_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsssource',
            name='last_updated_at',
            field=models.CharField(default=rss_scrapper.models.rss_source.now, max_length=255),
        ),
    ]
