# Generated by Django 4.0.2 on 2022-02-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_backup', '0002_alter_historicalpostbackup_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostbackup',
            name='title',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='postbackup',
            name='title',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
