# Generated by Django 4.0.2 on 2022-02-25 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_backup', '0003_historicalpostbackup_title_postbackup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostbackup',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 25, 9, 2, 22, 512794, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postbackup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
