# Generated by Django 4.0.2 on 2022-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemessage',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
