# Generated by Django 4.0.2 on 2022-02-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_onlinemessage_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinemessage',
            name='ghost_id',
        ),
        migrations.AddField(
            model_name='onlinemessage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
