# Generated by Django 4.0.2 on 2022-02-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_remove_onlinemessage_ghost_id_onlinemessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemessage',
            name='ghost_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
