# Generated by Django 4.0.2 on 2022-03-31 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_onlinemessage_ghost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemessage',
            name='media_group_id',
            field=models.CharField(default='', max_length=2055),
        ),
        migrations.CreateModel(
            name='OnlineAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('meta', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.onlinemessage')),
            ],
        ),
    ]
