# Generated by Django 4.0.2 on 2022-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_onlinemessage_media_group_id_onlineattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemessage',
            name='chat_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
