from .card import (
    CARD_WIDTH,
    LEFT_PADDING,
)

FOOTER_HEIGHT = 190
FOOTER_SIZE = (CARD_WIDTH, FOOTER_HEIGHT)
OPINION_PROFILE_IMAGE_WIDTH = 120
OPINION_PROFILE_IMAGE_SIZE = (OPINION_PROFILE_IMAGE_WIDTH, OPINION_PROFILE_IMAGE_WIDTH)

OPINION_NAME_COORDS = (LEFT_PADDING + OPINION_PROFILE_IMAGE_WIDTH + 20, 15)
OPINION_NAME_FONT_SIZE = 42

OPINION_BIO_FONT_SIZE = 24
OPINION_BIO_COORDS = (OPINION_NAME_COORDS[0], 70)
OPINION_BIO_FILL = (255, 255, 255, 127)

CONTEXT_EXCERPT_FONT_SIZE = 36
