from .card import CARD_WIDTH

HEADER_HEIGHT = 132
HEADER_SIZE = (CARD_WIDTH, HEADER_HEIGHT)
TEST_HEADER_HEIGHT = 403
TEST_HEADER_SIZE = (CARD_WIDTH, TEST_HEADER_HEIGHT)
TAG_Y_POSITION = 103
LOGO_X_POSITION = 795
