from .card import CARD_HEIGHT
from .header import HEADER_HEIGHT

TITLE_LAYER_HEIGHT = CARD_HEIGHT - HEADER_HEIGHT
OPINION_TITLE_LAYER_HEIGHT = 344
OPINION_TITLE_WIDTH = 25
OPINION_TITLE_MAX_LINES = 3

TITLE_SIZE = 58
TITLE_SPACING = 16

OPINION_TITLE_SIZE = 74
OPINION_TITLE_SPACING = 18

TITLE_FILL = (255, 255, 255, 255)
TITLE_WIDTH = 33
TITLE_MAX_LINES = 4
TITLE_PLACEHOLDER = '...'

FACTCHECKING_TITLE_LAYER_HEIGHT = 537
FACTCHECKING_METER_SIZE = (FACTCHECKING_TITLE_LAYER_HEIGHT, FACTCHECKING_TITLE_LAYER_HEIGHT)

FACTCHECKING_TITLE_TOP_PADDING = 80
FACTCHECKING_TITLE_WIDTH = 26
FACTCHECKING_TITLE_FONT_SIZE = 34
FACTCHECKING_TITLE_SPACING = FACTCHECKING_TITLE_FONT_SIZE / 2.5
FACTCHECKING_TITLE_MAX_LINES = 6
FACTCHECKING_DATE_FONT_SIZE = 24
FACTCHECKING_DATE_FILL = (255, 255, 255, 125)

TEST_TITLE_MAX_LINES = 2
