from .card import CARD_HEIGHT
from .header import HEADER_HEIGHT

TITLE_LAYER_HEIGHT = CARD_HEIGHT - HEADER_HEIGHT
OPINION_TITLE_LAYER_HEIGHT = 344
OPINION_TITLE_WIDTH = 25
OPINION_TITLE_MAX_LINES = 3

TITLE_SIZE = 58
TITLE_SPACING = 14

OPINION_TITLE_SIZE = 74
OPINION_TITLE_SPACING = 18

TITLE_FILL = (255, 255, 255, 255)
TITLE_WIDTH = 33
TITLE_MAX_LINES = 4
TITLE_PLACEHOLDER = '...'
