# Generated by Django 3.2.8 on 2022-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('json', models.TextField()),
            ],
        ),
    ]
