# Generated by Django 3.2.8 on 2022-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('json', models.TextField()),
            ],
        ),
    ]
